<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RollForward>Major</RollForward>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PlatformTarget>x64</PlatformTarget>
    <YargAudioNativeConfiguration Condition="'$(YargAudioNativeConfiguration)' == ''">Release</YargAudioNativeConfiguration>
  </PropertyGroup>

  <Target Name="CopyNativeDependencies" AfterTargets="Build">
    <Copy
      SourceFiles="../../../../Assets/Plugins/BassNative/Windows/x86_64/bass.dll;../../build/windows-x64/$(YargAudioNativeConfiguration)/yarg_audio.dll"
      DestinationFolder="$(OutputPath)" />
  </Target>
</Project>
